#!/usr/bin/env node
/**
 * Builds core/vendor/subtls.mjs: the TLS 1.3 client from jawj/subtls (MIT), cut down to what
 * core/proxy.ts uses, as one ES module with no imports. Workers here build with wrangler alone and
 * have no npm dependencies, and subtls's npm build imports Node's `net`, so it is vendored instead.
 *
 *   node scripts/vendor-subtls.mjs
 *
 * Built from the commit pinned below, with two changes, each checked to apply exactly once:
 *   - `chatty` is off, so none of the annotated logging is kept.
 *   - A certificate counts as valid from five minutes before its notBefore. Apify mints a
 *     certificate for each site at the moment it is asked, so notBefore is the current second,
 *     and a Worker clock a little behind Apify's would otherwise refuse it.
 * Node's `crypto` is never reached in a Worker (Web Crypto is global), so it is stubbed out.
 */
import { execFileSync } from "node:child_process";
import { copyFileSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { build } from "esbuild";

const REPO = "https://github.com/jawj/subtls.git";
const COMMIT = "6e7949a55c1715df2c8f2b04286e19c2a3e8bec8";
const OUT = "core/vendor/subtls.mjs";

const dir = mkdtempSync(join(tmpdir(), "subtls-"));
try {
  const git = (...args) => execFileSync("git", args, { cwd: dir, stdio: "inherit" });
  git("init", "-q");
  git("fetch", "-q", "--depth", "1", REPO, COMMIT);
  git("checkout", "-q", "FETCH_HEAD");
  execFileSync("npm", ["ci", "--ignore-scripts", "--no-audit", "--no-fund", "--silent"], {
    cwd: dir,
    stdio: "inherit",
  });

  const patch = (file, from, to) => {
    const path = join(dir, file);
    const src = readFileSync(path, "utf8");
    if (src.split(from).length !== 2) throw new Error(`${file}: expected one match of ${from}`);
    writeFileSync(path, src.replace(from, to));
  };
  patch(
    "src/tls/cert.ts",
    "return moment >= this.validityPeriod.notBefore && moment <= this.validityPeriod.notAfter;",
    "return moment.getTime() >= this.validityPeriod.notBefore.getTime() - 300_000 && moment <= this.validityPeriod.notAfter;",
  );

  writeFileSync(
    join(dir, "entry.ts"),
    [
      "export { startTls } from './src/tls/startTls';",
      "export { TrustedCert } from './src/tls/cert';",
    ].join("\n"),
  );

  const result = await build({
    entryPoints: [join(dir, "entry.ts")],
    bundle: true,
    format: "esm",
    target: "es2022",
    platform: "neutral",
    define: { chatty: "0" },
    write: false,
    plugins: [
      {
        name: "no-node-crypto",
        setup(b) {
          b.onResolve({ filter: /^crypto$/ }, () => ({ path: "crypto", namespace: "stub" }));
          b.onLoad({ filter: /.*/, namespace: "stub" }, () => ({
            contents: "export const webcrypto = globalThis.crypto;",
          }));
        },
      },
    ],
  });
  const code = result.outputFiles[0].text;
  if (/\bfrom\s+["']|\bimport\s*\(/.test(code))
    throw new Error("the bundle still imports something");

  writeFileSync(
    OUT,
    `// Generated by scripts/vendor-subtls.mjs from ${REPO} at ${COMMIT}. Do not edit.\n` +
      `// MIT licence: core/vendor/subtls.LICENSE.\n` +
      code,
  );
  copyFileSync(join(dir, "LICENSE"), "core/vendor/subtls.LICENSE");
  console.log(`wrote ${OUT} (${code.length} bytes)`);
} finally {
  rmSync(dir, { recursive: true, force: true });
}
